opcalendar/urls.py
from django.urls import path

from . import views

app_name = 'opcalendar'
urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:event_id>/remove', views.EventDeleteView, name="remove_event"),
]

opcalendar/models.py
import requests
import json

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

from allianceauth.eveonline.models import EveCharacter

from django.utils.translation import ugettext_lazy as _
# Create your models here.

class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ("basic_access", "Can access this app"),
            ("view_public", "Can see public events"),
            ("view_member", "Can see member events"),
            ("create_event", "Can create and edit events"),
            ("manage_event", "Can delete and manage signups"),
        )     

class WebHook(models.Model):
    """Discord Webhook for pings"""
    name = models.CharField(max_length=150)
    webhook_url = models.CharField(max_length=500)
    enabled = models.BooleanField()

    def send_embed(self, embed):
        custom_headers = {'Content-Type': 'application/json'}
        data = '{"embeds": [%s]}' % json.dumps(embed)
        r = requests.post(self.webhook_url, headers=custom_headers,
                            data=data)
        r.raise_for_status()

    class Meta:
        verbose_name = 'Webhook'
        verbose_name_plural = 'Webhooks'

    def __str__(self):
        return '{}'.format(self.name)

class EventSignal(models.Model):
    """Fleet Timer Create/Delete pings"""

    webhook = models.ForeignKey(WebHook, on_delete=models.CASCADE)

    ignore_past_fleets = models.BooleanField(default=True)

    def __str__(self):
        return 'Send Fleets to "{}"'.format(self.webhook.name)

    class Meta:
        verbose_name = 'Fleet Signal'
        verbose_name_plural = 'Fleet Signals'    

class EventHost(models.Model):
    """Fleet Timer Create/Delete pings"""

    community = models.CharField(max_length=150, null=False)
    ingame_channel = models.CharField(max_length=150, blank=True)
    ingame_mailing_list = models.CharField(max_length=150, blank=True)
    fleet_comms = models.CharField(max_length=150, blank=True)
    fleet_doctrines = models.CharField(max_length=150, blank=True)
    website = models.CharField(max_length=150, blank=True)
    discord = models.CharField(max_length=150, blank=True)
    twitch = models.CharField(max_length=150, blank=True)
    twitter = models.CharField(max_length=150, blank=True)
    youtube = models.CharField(max_length=150, blank=True)
    facebook = models.CharField(max_length=150, blank=True)
    details = models.CharField(max_length=150, blank=True)
   
    def __str__(self):
        return str(self.community)

    class Meta:
        verbose_name = 'Host'
        verbose_name_plural = 'Hosts'           

class EventCategory(models.Model):
    # Colors for calendar
    COLOR_BLUE = "blue"
    COLOR_GREEN = "green"
    COLOR_RED = "red"
    COLOR_ORANGE = "orange"  
    COLOR_GREY = "grey"
    COLOR_YELLOW = "yellow"
    COLOR_PURPLE = "purple"

    COLOR_CHOICES = (
        (COLOR_GREEN, _("Green")),
        (COLOR_RED, _("Red")),
        (COLOR_ORANGE, _("Orange")),
        (COLOR_BLUE, _("Blue")),
        (COLOR_GREY, _("Grey")),
        (COLOR_YELLOW, _("Yellow")),
        (COLOR_PURPLE, _("Purple")),

    )
    name = models.CharField(max_length=150)
    ticker = models.CharField(max_length=10) 
    color = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return str(self.name)

class EventImport(models.Model):
    """NPSI IMPORT OPTIONS"""
    SPECTRE_FLEET = "Spectre Fleet"
    EVE_UNIVERSITY = "EVE University"
    
    IMPORT_SOURCES = (
        (SPECTRE_FLEET, _("Spectre Fleet")),
        (EVE_UNIVERSITY, _("EVE University")),
        )

    source = models.CharField(
        max_length=32,
        choices=IMPORT_SOURCES,
        help_text="The API source where you want to pull events from"
    )
    
    host = models.ForeignKey(
        EventHost, on_delete=models.CASCADE,
        default=1,
        help_text="The AA host that will be used for the pulled events"
    )
    operation_type = models.ForeignKey(
        EventCategory,
        on_delete=models.CASCADE,
        help_text="Operation type and ticker that will be assigned for the pulled fleets"
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default='1',
        help_text="User that has been used to create the fleet (most often the superuser who manages the plugin)"
    )
    eve_character = models.ForeignKey(
        EveCharacter,
        null=True,
        on_delete=models.SET_NULL,
        help_text="Event creator main character"
    )
   
    def __str__(self):
        return str(self.source)

    class Meta:
        verbose_name = 'Event Import'
        verbose_name_plural = 'Event Imports'   

class Event(models.Model):
    # visibility
    VISIBILITY_PUBLIC = "public"
    VISIBILITY_MEMBER = "member"
    VISIBILITY_EXTERNAL = "import"

    VISIBILITY_CHOICES = [
        (VISIBILITY_PUBLIC, _("Public access")),
        (VISIBILITY_MEMBER, _("Members only access")),
    ]


    operation_type = models.ForeignKey(
        EventCategory, 
        on_delete=models.CASCADE
    )
    title = models.CharField(
        max_length=200, 
        unique=False
    )
    host = models.ForeignKey(
        EventHost, 
        on_delete=models.CASCADE, 
        default=1
    )
    doctrine = models.CharField(
        max_length=254, 
        default="", 
        blank=True
    )
    formup_system = models.CharField(
        max_length=254, 
        default="", 
        blank=True
    )
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    fc = models.CharField(
        max_length=254, 
        default=""
    )
    visibility = models.CharField(
        max_length=7,
        choices=VISIBILITY_CHOICES,
        default=VISIBILITY_PUBLIC,
        db_index=True,
    )
    created_date = models.DateTimeField(
        default=timezone.now
    )
    eve_character = models.ForeignKey(
        EveCharacter,
        null=True,
        on_delete=models.SET_NULL
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ['title', 'start_time']

    def duration(self):
        return self.end_time - self.start_time

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('opcalendar:event-detail', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('opcalendar:event-detail', args=(self.id,))
        return f'{url}'

    @property
    def get_html_title(self):
        return f'{self.start_time.strftime("%H:%M")} - {self.end_time.strftime("%H:%M")} <i>{self.host.community}</i> <br> <b>{self.operation_type.ticker} {self.title}</b>'
    @property
    def get_html_operation_color(self):
        return f'{self.operation_type.color}'

    @property
    def get_html_visibility_color(self):
        if self.visibility=="public":
            return "purple"
        if self.visibility=="import":
            return "grey"
        if self.visibility=="member":   
            return "blue"

    def user_can_edit(self, user: user) -> bool:
        """Checks if the given user can edit this timer. Returns True or False"""
        return user.has_perm("opcalendar.manage_event") or (
            self.user == user and user.has_perm("opcalendar.create_event")
        )

class EventMember(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['event', 'user']

    def __str__(self):
        return str(self.user)

    

opcalendar/templates/opcalendar/add_member.html
{% extends 'opcalendar/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'opcalendar:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

opcalendar/templates/opcalendar/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'opcalendar/style.css' %}">
{% endblock extra_css %}
{% block page_title %}{% trans title %}{% endblock %}

{% block content %}    
    <h2 class="text-center">{{ title }}</h2>
    <div class="col-lg-14 container">            
        {% block details %}{% endblock %}
    </div>
{% endblock %}
{% block extra_script %}

    $('#id_start_time').datetimepicker({
    setlocale: '{{ LANGUAGE_CODE }}',
    {% if NIGHT_MODE %}
        theme: 'dark',
    {% else %}
        theme: 'default',
    {% endif %}
    mask: true,
    format: 'Y-m-d H:i',
    minDate: 0
    });

    $('#id_end_time').datetimepicker({
    setlocale: '{{ LANGUAGE_CODE }}',
    {% if NIGHT_MODE %}
        theme: 'dark',
    {% else %}
        theme: 'default',
    {% endif %}
    mask: true,
    format: 'Y-m-d H:i',
    minDate: 0
    });

{% endblock extra_script %}

opcalendar/templates/opcalendar/calendar.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load evelinks %}
{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}

{% block content %}

<div class="clearfix">
	<a class="btn btn-info right mr-2" href="{% url 'opcalendar:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'opcalendar:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    {% if perms.opcalendar.create_event %}
    	<a class="btn btn-info right mr-2" href="{% url 'opcalendar:event_new' %}"> + New Event </a>
    {% endif %}
    <h5>Legend & Filters:</h5>
    <div class="legend">
    	<div>
    		<span class="event import-event">Third Party Event</span>
    		<span class="event public-event">Public Event</span>
    		<span class="event member-event">Members Only Event</span>
    	</div>
    	<div>
    		{% for event in category %}
    			<span class="event {{ event.color }}">{{ event.name }}</span>
    		{% endfor %}
    	</div>
    </div>
</div>
<div>
    {{ calendar }}
</div>
{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
    <script>
		$('.legend div:first-child').prepend('<span class="event show-all">Show all</span>')

		$('.legend').on('click', 'span', function(){
		    const classes = $(this).attr('class')
		    const selectors = '.' + classes.split(' ').join('.')
		    applyCalendarFilters(selectors)
		})

		function applyCalendarFilters(selectors){
		    $('.calendar .event').hide()
		    $('.legend span').removeClass('active')

		    if(selectors.includes('show-all')){
		        $('.calendar .event').show()
		        $('.legend .show-all').addClass('active')
		    }
		    else{
		        $('.calendar ' + selectors).show()
		        $('.legend ' + selectors).addClass('active')
		    }
		}
    </script>
{% endblock %}

opcalendar/templates/opcalendar/event-add.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}
{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Create New Event" %}</h1>

        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Create New Event" %}</button>
                        </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
{% endblock %}

opcalendar/templates/opcalendar/event-details.html
{% extends 'opcalendar/base.html' %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'opcalendar:calendar' %}"> Calendar </a>
            {% if perms.opcalendar.create_event %}
                <a class="btn btn-primary left mr-2" href="{% url 'opcalendar:event_edit' event.pk %}"> Edit Event </a>
                <a class="btn btn-danger" href="{% url 'opcalendar:remove_event' event.id %}">Remove</a>
            {% endif %}
        </div>
        
        <div class="clearfix">
            <div class="col-lg-12 text-center row">
            <div class="label label-info text-left">
                <b>{% trans "Current Eve Time:" %} </b>
            </div>
            <strong class="label label-info text-left" id="current-time"></strong>
            <br  />
        </div>
            <h2>{{ event.title }}</h2>
            <p>Created by: <span style="color: gray;">{{ event.eve_character }}</span> Starts in: <span id="countdown{{ event.id }}" style="color: gray;">{{ event.eve_character }}</span></p>
            <hr>
            <h4>Event details</h4>
            <table>
                <tr>
                    <td style="padding-right: 10px;"><b>Type:</b></td>
                    <td><span class="event {{ event.operation_type.color }}">{{ event.operation_type }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Availability:</b></td>
                    <td><span class="event {{ event.get_html_visibility_color }}">{{ event.visibility }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Start time:</b></td>
                    <td>{{ event.start_time|date:"D Y-m-d H:i" }} (EVE) / <span id="localtime{{ event.id }}"></span> (Local)</td>
                </tr>

                <tr>
                    <td style="padding-right: 10px;"><b>Est. end time:</b></td>
                    <td>{{ event.end_time|date:"D Y-m-d H:i" }}</td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Duration:</b></td>
                    <td>{{ event.duration }}</td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Formup location:</b></td>
                    <td>{{ event.formup_system }}</td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Doctrine:</b></td>
                    <td>{{ event.doctrine }}</td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Fleet Commander:</b></td>
                    <td>{{ event.fc }}</td>
                </tr>
            </table>
            <p style="padding-top:40px">{{ event.description|striptags|urlize}}</p>   
            <hr>
            <h4>Host details</h4>
            <table>
                <tr>
                    <td style="padding-right: 10px;"><b>Community:</b></td>
                    <td><span>{{ event.host.community|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Ingame channel:</b></td>
                    <td><span>{{ event.host.ingame_channel|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Ingame mailing list:</b></td>
                    <td><span>{{ event.host.ingame_mailing_list|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Fleet comms:</b></td>
                    <td><span>{{ event.host.fleet_comms|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Fleet doctrines:</b></td>
                    <td><span>{{ event.host.fleet_doctrines|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Website:</b></td>
                    <td><span>{{ event.host.website|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Discord:</b></td>
                    <td><span>{{ event.host.discord|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Twitch:</b></td>
                    <td><span>{{ event.host.twitch|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Twitter:</b></td>
                    <td><span>{{ event.host.twitter|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Youtube:</b></td>
                    <td><span>{{ event.host.youtube|urlize }}</span></td>
                </tr>
                <tr>
                    <td style="padding-right: 10px;"><b>Facebook:</b></td>
                    <td><span>{{ event.host.facebook|urlize }}</span></td>
                </tr>             
            </table>
            <p style="padding-top:40px">{{ event.host.details }}</p> 
        </div>
    </div>
{% include 'bundles/moment-js.html' with locale=True %}
    <script src="{% static 'js/timers.js' %}"></script>
    <script type="application/javascript">
        // Data
        var timers = [
            {
                'id': {{ event.id }},
                'start': moment("{{ event.start_time | date:"c" }}"),
                'expired': false
            },
        ];
    </script>
    <script type="application/javascript">

        timedUpdate();
        setAllLocalTimes();

        // Start timed updates
        setInterval(timedUpdate, 1000);

        function timedUpdate() {
            updateClock();
            updateAllTimers();
        }

        function updateAllTimers () {
            var l = timers.length;
            for (var i=0; i < l; ++i) {
                if (timers[i].expired) continue;
                updateTimer(timers[i]);
            }
        }

        /**
         * Update a timer
         * @param timer Timer information
         * @param timer.start Date of the timer
         * @param timer.id Id number of the timer
         * @param timer.expired
         */
        function updateTimer(timer) {
            if (timer.start.isAfter(Date.now())) {
                var duration = moment.duration(timer.start - moment(), 'milliseconds');
                document.getElementById("countdown" + timer.id).innerHTML = getDurationString(duration);
            } else {
                timer.expired = true;
                document.getElementById("countdown" + timer.id).innerHTML = "";
            }
        }

        /**
         * Set all local time fields
         */
        function setAllLocalTimes() {
            var l = timers.length;
            for (var i=0; i < l; ++i) {
                setLocalTime(timers[i]);
            }
        }

        /**
         * Set the local time info for the timer
         * @param timer Timer information
         * @param timer.start Date of the timer
         * @param timer.id Id number of the timer
         */
        function setLocalTime(timer) {
            document.getElementById("localtime" + timer.id).innerHTML = timer.start.format("ddd MM-DD HH:mm");
        }

        function updateClock() {
            document.getElementById("current-time").innerHTML = getCurrentEveTimeString();
        }
    </script>
{% endblock %}

opcalendar/templates/opcalendar/event-edit.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}
{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Edit Event" %}</h1>
        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Edit Event" %}</button>
                        </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
{% endblock %}

opcalendar/templates/opcalendar/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'opcalendar/base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

opcalendar/templates/opcalendar/signup.html
{% extends 'opcalendar/base.html' %}

{% block title %} Signup {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6  m-2">
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary mt-2" type="submit" value="Signup">
        </form>
    </div>
</div>
{% endblock %}